### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by Freedom645**
Merge.

### CODE REVIEW

**Comment by hokekyo1210** [comment]
NO

**Comment by hokekyo1210** [comment]
THIS BRANCH IS INCLUDING BUG

**Comment by Freedom645** [comment]
Oh No...

**Comment by hokekyo1210** [comment]
lie

**Comment by hokekyo1210** [comment]
:)

**Comment by Freedom645** [comment]
You are like RIKUMA.

**Pull request merged**
